#!/usr/bin/sh

sxhkd &
compton &
xcape

bspc monitor DP-1 -d I II
bspc monitor DVI-D-0 -d III IV V
bspc monitor DP-5 -d VI VII
bspc monitor HDMI-0 -d VIII IX X

bspc config border_width         2
bspc config window_gap           20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a \*:"URxvtFuzzy" state=floating center=on sticky=on
